server:
  port: 8084
spring:
  application:
    name: restaurant (command side)
axon:
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100

axoniq:
  axonhub:
    servers: localhost
