server:
  port: 8084
spring:
  data:
    rest:
      base-path: /api/query/restaurant
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      restaurant:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100