server:
  port: 8081
spring:
  data:
    rest:
      base-path: /api/query/courier
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      courier:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        courier: 100
        courierorder: 100
