server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:restaurant-customer
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        customer: 100
        customerorder: 100