server:
  port: 8082
spring:
  data:
    rest:
      base-path: /api/query/customer
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console