server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:mem:restaurant-restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100