server:
  port: 8085
spring:
  data:
    rest:
      base-path: /api/query
  datasource:
    url: jdbc:h2:mem:restaurant-query
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      customer:
        mode: tracking
      restaurant:
        mode: tracking
      order:
        mode: tracking
      courier:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100