spring:
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      customer:
        mode: tracking
      restaurant:
        mode: tracking
      order:
        mode: tracking
      courier:
        mode: tracking
      courierorder:
        mode: tracking
      restaurantorder:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        order: 200
        restaurant: 200
        customer: 200
        courier: 200
        customerorder: 200
        courierorder: 200
        restaurantorder: 200

axoniq:
  axonhub:
    servers: localhost
server:
  port: 8080